const emojiConfig = {
  categories: [
    {
      name: "playback",
      priority: 1,
      emojis: [
        {
          botName: "play",
          discordName: "play",
          fallback: "▶️",
          description: "Play button",
        },
        {
          botName: "pause",
          discordName: "pause",
          fallback: "⏸️",
          description: "Pause button",
        },
        {
          botName: "stop",
          discordName: "stop",
          fallback: "⏹️",
          description: "Stop button",
        },
        {
          botName: "skip",
          discordName: "skip",
          fallback: "⏭️",
          description: "Skip to next track",
        },
        {
          botName: "previous",
          discordName: "previous",
          fallback: "⏮️",
          description: "Previous track",
        },
        {
          botName: "shuffle",
          discordName: "shuffle",
          fallback: "🔀",
          description: "Shuffle queue",
        },
        {
          botName: "loop",
          discordName: "loop",
          fallback: "🔁",
          description: "Loop queue/track",
        },
        {
          botName: "loop_track",
          discordName: "loop_track",
          fallback: "🔂",
          description: "Loop single track",
        },
        {
          botName: "queue",
          discordName: "queue",
          fallback: "📋",
          description: "Queue list",
        },
        {
          botName: "now_playing",
          discordName: "now_playing",
          fallback: "🎵",
          description: "Now playing",
        },
      ],
    },
    {
      name: "progress_bar",
      priority: 0,
      emojis: [
        {
          botName: "pb_start",
          discordName: "pb_start",
          fallback: "╺",
          description: "Progress bar start",
        },
        {
          botName: "pb_filled",
          discordName: "pb_filled",
          fallback: "━",
          description: "Progress bar filled",
        },
        {
          botName: "pb_empty",
          discordName: "pb_empty",
          fallback: "─",
          description: "Progress bar empty",
        },
        {
          botName: "pb_head",
          discordName: "pb_head",
          fallback: "●",
          description: "Progress bar head",
        },
        {
          botName: "pb_end",
          discordName: "pb_end",
          fallback: "╸",
          description: "Progress bar end",
        },
        {
          botName: "pb_start_filled",
          discordName: "pb_start_filled",
          fallback: "┣",
          description: "Progress bar start filled",
        },
        {
          botName: "pb_end_filled",
          discordName: "pb_end_filled",
          fallback: "┫",
          description: "Progress bar end filled",
        },
      ],
    },
    {
      name: "player_ui",
      priority: 0,
      description: "Player interface emojis for enhanced embed",
      emojis: [
        {
          botName: "fx",
          discordName: "fx",
          fallback: "🎛️",
          description: "Audio effects button",
        },
        {
          botName: "ping_good",
          discordName: "ping_good",
          fallback: "🟢",
          description: "Good connection quality",
        },
        {
          botName: "ping_medium",
          discordName: "ping_medium",
          fallback: "🟡",
          description: "Medium connection quality",
        },
        {
          botName: "ping_bad",
          discordName: "ping_bad",
          fallback: "🔴",
          description: "Poor connection quality",
        },
        {
          botName: "sparkle",
          discordName: "sparkle",
          fallback: "✨",
          description: "Sparkle effect",
        },
        {
          botName: "fire",
          discordName: "fire",
          fallback: "🔥",
          description: "Fire/hot indicator",
        },
        {
          botName: "crown",
          discordName: "crown",
          fallback: "👑",
          description: "Premium/VIP indicator",
        },
        {
          botName: "trophy",
          discordName: "trophy",
          fallback: "🏆",
          description: "Top track indicator",
        },
        {
          botName: "album",
          discordName: "album",
          fallback: "💿",
          description: "Album indicator",
        },
        {
          botName: "divider",
          discordName: "divider",
          fallback: "•",
          description: "Section divider",
        },
        {
          botName: "arrow_right",
          discordName: "arrow_right",
          fallback: "➤",
          description: "Right arrow",
        },
        {
          botName: "diamond",
          discordName: "diamond",
          fallback: "◆",
          description: "Diamond bullet",
        },
      ],
    },
    {
      name: "sources",
      priority: 1,
      emojis: [
        {
          botName: "source_spotify",
          discordName: "spotify",
          fallback: "🎵",
          description: "Spotify source",
        },
        {
          botName: "source_youtube",
          discordName: "youtube",
          fallback: "📺",
          description: "YouTube source",
        },
        {
          botName: "source_soundcloud",
          discordName: "soundcloud",
          fallback: "☁️",
          description: "SoundCloud source",
        },
        {
          botName: "source_apple",
          discordName: "applemusic",
          fallback: "🍎",
          description: "Apple Music source",
        },
        {
          botName: "source_deezer",
          discordName: "deezer",
          fallback: "🎧",
          description: "Deezer source",
        },
      ],
    },
    {
      name: "filters",
      priority: 2,
      emojis: [
        {
          botName: "bassboost",
          discordName: "bassboost",
          fallback: "🎸",
          description: "Bass boost filter",
        },
        {
          botName: "equalizer",
          discordName: "equalizer",
          fallback: "🎚️",
          description: "Equalizer",
        },
        {
          botName: "boost",
          discordName: "boost",
          fallback: "📈",
          description: "Boost filter",
        },
        {
          botName: "soft",
          discordName: "soft",
          fallback: "🌊",
          description: "Soft filter",
        },
        {
          botName: "bass",
          discordName: "bass",
          fallback: "🎧",
          description: "Bass filter",
        },
        {
          botName: "deepbass",
          discordName: "deepbass",
          fallback: "💥",
          description: "Deep bass filter",
        },
        {
          botName: "superbass",
          discordName: "superbass",
          fallback: "👾",
          description: "Super bass filter",
        },
        {
          botName: "flat",
          discordName: "flat",
          fallback: "📐",
          description: "Flat filter",
        },
        {
          botName: "warm",
          discordName: "warm",
          fallback: "🔥",
          description: "Warm filter",
        },
        {
          botName: "metal",
          discordName: "metal",
          fallback: "🤘",
          description: "Metal filter",
        },
        {
          botName: "oldschool",
          discordName: "oldschool",
          fallback: "📻",
          description: "Old school filter",
        },
        {
          botName: "classical",
          discordName: "classical",
          fallback: "🎻",
          description: "Classical filter",
        },
        {
          botName: "electronic",
          discordName: "electronic",
          fallback: "🎹",
          description: "Electronic filter",
        },
        {
          botName: "hiphop",
          discordName: "hiphop",
          fallback: "🎤",
          description: "Hip-hop filter",
        },
        {
          botName: "jazz",
          discordName: "jazz",
          fallback: "🎷",
          description: "Jazz filter",
        },
        {
          botName: "pop",
          discordName: "pop",
          fallback: "⭐",
          description: "Pop filter",
        },
        {
          botName: "reggae",
          discordName: "reggae",
          fallback: "☀️",
          description: "Reggae filter",
        },
        {
          botName: "rock",
          discordName: "rock",
          fallback: "🎸",
          description: "Rock filter",
        },
        {
          botName: "gaming",
          discordName: "gaming",
          fallback: "🎮",
          description: "Gaming filter",
        },
        {
          botName: "nightcore",
          discordName: "nightcore",
          fallback: "🌙",
          description: "Nightcore filter",
        },
        {
          botName: "vaporwave",
          discordName: "vaporwave",
          fallback: "🧉",
          description: "Vaporwave filter",
        },
        {
          botName: "vocals",
          discordName: "vocals",
          fallback: "🎼",
          description: "Vocals filter",
        },
        {
          botName: "bright",
          discordName: "bright",
          fallback: "💡",
          description: "Bright filter",
        },
        {
          botName: "treble",
          discordName: "treble",
          fallback: "📶",
          description: "Treble filter",
        },
        {
          botName: "reset",
          discordName: "reset",
          fallback: "🔄",
          description: "Reset filters",
        },
      ],
    },
    {
      name: "status",
      priority: 3,
      emojis: [
        {
          botName: "playing",
          discordName: "playing",
          fallback: "🎵",
          description: "Currently playing",
        },
        {
          botName: "loading",
          discordName: "loading",
          fallback: "⏳",
          description: "Loading",
        },
        {
          botName: "error",
          discordName: "error",
          fallback: "❌",
          description: "Error",
        },
        {
          botName: "success",
          discordName: "success",
          fallback: "✅",
          description: "Success",
        },
        {
          botName: "warning",
          discordName: "warning",
          fallback: "⚠️",
          description: "Warning",
        },
        {
          botName: "info",
          discordName: "info",
          fallback: "ℹ️",
          description: "Information",
        },
        {
          botName: "search",
          discordName: "search",
          fallback: "🔍",
          description: "Search",
        },
        {
          botName: "music",
          discordName: "music",
          fallback: "🎶",
          description: "Music",
        },
        {
          botName: "playlist",
          discordName: "playlist",
          fallback: "📝",
          description: "Playlist",
        },
        {
          botName: "volume_up",
          discordName: "volume_up",
          fallback: "🔊",
          description: "Volume up",
        },
        {
          botName: "volume_down",
          discordName: "volume_down",
          fallback: "🔉",
          description: "Volume down",
        },
        {
          botName: "volume_mute",
          discordName: "volume_mute",
          fallback: "🔇",
          description: "Volume mute",
        },
        {
          botName: "repeat_one",
          discordName: "repeat_one",
          fallback: "🔂",
          description: "Repeat one",
        },
        {
          botName: "forward",
          discordName: "forward",
          fallback: "⏩",
          description: "Forward",
        },
        {
          botName: "rewind",
          discordName: "rewind",
          fallback: "⏪",
          description: "Rewind",
        },
        {
          botName: "seek",
          discordName: "seek",
          fallback: "🎯",
          description: "Seek",
        },
        {
          botName: "replay",
          discordName: "replay",
          fallback: "🔃",
          description: "Replay",
        },
        {
          botName: "autoplay",
          discordName: "autoplay",
          fallback: "📻",
          description: "Autoplay",
        },
        {
          botName: "lyrics",
          discordName: "lyrics",
          fallback: "📜",
          description: "Lyrics",
        },
      ],
    },
    {
      name: "voice_status",
      priority: 4,
      emojis: [
        {
          botName: "online",
          discordName: "online",
          fallback: "🟢",
          description: "Online status",
        },
        {
          botName: "idle",
          discordName: "idle",
          fallback: "🟡",
          description: "Idle status",
        },
        {
          botName: "dnd",
          discordName: "dnd",
          fallback: "🔴",
          description: "Do not disturb",
        },
        {
          botName: "offline",
          discordName: "offline",
          fallback: "⚫",
          description: "Offline status",
        },
        {
          botName: "streaming",
          discordName: "streaming",
          fallback: "🟣",
          description: "Streaming",
        },
        {
          botName: "mic_on",
          discordName: "mic_on",
          fallback: "🎙️",
          description: "Microphone on",
        },
        {
          botName: "mic_off",
          discordName: "mic_off",
          fallback: "🔇",
          description: "Microphone off",
        },
        {
          botName: "speaker_on",
          discordName: "speaker_on",
          fallback: "🔊",
          description: "Speaker on",
        },
        {
          botName: "speaker_off",
          discordName: "speaker_off",
          fallback: "🔈",
          description: "Speaker off",
        },
      ],
    },
    {
      name: "navigation",
      priority: 4,
      emojis: [
        {
          botName: "home",
          discordName: "home",
          fallback: "🏠",
          description: "Home",
        },
        {
          botName: "back",
          discordName: "back",
          fallback: "⬅️",
          description: "Back",
        },
        {
          botName: "forward_nav",
          discordName: "forward",
          fallback: "➡️",
          description: "Forward",
        },
        {
          botName: "refresh",
          discordName: "refresh",
          fallback: "🔄",
          description: "Refresh",
        },
        {
          botName: "settings",
          discordName: "settings",
          fallback: "⚙️",
          description: "Settings",
        },
        {
          botName: "help",
          discordName: "help",
          fallback: "❓",
          description: "Help",
        },
      ],
    },
    {
      name: "actions",
      priority: 5,
      emojis: [
        {
          botName: "add",
          discordName: "add",
          fallback: "➕",
          description: "Add",
        },
        {
          botName: "remove",
          discordName: "remove",
          fallback: "➖",
          description: "Remove",
        },
        {
          botName: "link",
          discordName: "link",
          fallback: "🔗",
          description: "Link",
        },
        {
          botName: "external",
          discordName: "external",
          fallback: "🌐",
          description: "External link",
        },
        {
          botName: "heart",
          discordName: "heart",
          fallback: "❤️",
          description: "Favorite",
        },
        {
          botName: "star",
          discordName: "star",
          fallback: "⭐",
          description: "Star",
        },
        {
          botName: "delete",
          discordName: "delete",
          fallback: "🗑️",
          description: "Delete",
        },
        {
          botName: "edit",
          discordName: "edit",
          fallback: "✏️",
          description: "Edit",
        },
        {
          botName: "save",
          discordName: "save",
          fallback: "💾",
          description: "Save",
        },
        {
          botName: "cancel",
          discordName: "cancel",
          fallback: "🚫",
          description: "Cancel",
        },
        {
          botName: "confirm",
          discordName: "confirm",
          fallback: "✔️",
          description: "Confirm",
        },
        {
          botName: "upload",
          discordName: "upload",
          fallback: "📤",
          description: "Upload",
        },
        {
          botName: "download",
          discordName: "download",
          fallback: "📥",
          description: "Download",
        },
        {
          botName: "search",
          discordName: "search",
          fallback: "🔎",
          description: "Search",
        },
        {
          botName: "filter",
          discordName: "filter",
          fallback: "🔣",
          description: "Filter",
        },
        {
          botName: "sort",
          discordName: "sort",
          fallback: "📊",
          description: "Sort",
        },
        {
          botName: "move",
          discordName: "move",
          fallback: "🔀",
          description: "Move",
        },
        {
          botName: "bump",
          discordName: "bump",
          fallback: "⬆️",
          description: "Bump",
        },
      ],
    },
  ],
};

export default emojiConfig;
